### ISSUE TITLE
App and methodology

### ISSUE THREAD

**Issue by ClarenceDowSpielman** [ClarenceDowSpielman/project-prep#10]
Can use the app 'out of the box', but may take training to use specifically to implement my methodology.  Are we keeping the app and methodology separate at this juncture?

**Comment by dazzaji** [comment]
Can you describe an example of how you currently work that shows both the methodology (whatever steps or other procedures etc you consider to be your method) and also demonstrates how you use Google Spreadsheets (connecting the technology tool and technical processes involved with data input, organization, storage and use)?  

Based on your example I can probably help you establish a workable forward looking approach to define and "containerize" method apart from "application" so you can maintain at least a general boundary between the two. 

Expect there to be some blurry lines and also be aware that those usually don't matter too much at time of prototype so long as you have things roughly well thought out.

**Comment by ClarenceDowSpielman** [comment]
Example work with H:

A typical Monday.  I begin by creating a new Evernote to record my data.  I track 19 categories for H which includes waiting time, transitions, social interactions, self-determination and self-advocacy.  Each time H performs in any of these categories, he scores points according to the level of performance (I use the language of weak, normal, and critical attacks).  Unlike traditional point-based reward systems, H earns 'experience points' even for his 'weak attacks', such as swearing when asked to transition from taking a break to doing work.

These categories were created taking into consideration H's transition goals (coming from a formal assessment through the school district.  Transition meaning what skills and behaviors does he need to gain and replace in order to succeed in the next phase of his life) as well as his own personal goals.

We start by doing a self-review of H's academic session, which has just ended.  H has a piece of paper graph his 'Time on Task' for the day, as well as a sheet of pros and cons.  We sign off on these everyday.  H knows that he can earn experience points for doing this self-review.

Since it is Monday, we then move to our 'LCS Debrief'.  On the previous Friday, I took all my Evernotes from that week's sessions and plug all of the experience points that H has earned into a Google Spreadsheet.  This spreadsheet then calculates how many experience points H has earned in each category for the week, the total for each day, and the total for the week.  H gains levels for earning a set amount of xp.  After I calculate the number of levels gained, I open another spreadsheet.  This is the spreadsheet I use for LCS debriefs.  It is a numbers sheet, because I do not have wifi access in the office where H and I do our work together.

When we do our LCS debrief on Monday, we start by pulling up the numbers spreadsheet.  It contains 5 graphs and data sets:
Line graph of total xp from week to week
Pie graphs of the past 2 weeks, showing a percentage of total xp breakdown of all 19 categories 
Bar graph of each category over each week
Line graphs of previous 2 weeks showing xp earned each day
Line graph highlighting one of the 19 categories

As we go through each one, we analyze data and identify trends, come up with top 5 category earners, and compare this week to past week.  I teach H how to interact with the spreadsheet, thus encouraging him to take ownership as an 'agent'.   I focus on using language like 'You are an agent - all agents get debriefed after completing their missions'.

This usually takes between 15 and 25 minutes.

Whatever else happens in our session, I use Evernotes in the moment to capture.  I have a shorthand developed to streamline my process of transferring data to the Google Spreadsheet at the end of the week.  I will often make notes next to events where xp is earned in multiple categories.

For example:

H sees two mints in my car.  He asks if I want one.  I prompt him to consider asking if he could have one.  He says oh, okay, can I have one?  I say yes.  I am about to pocket mine, when he says you should just eat that now.  Knowing that H has impulse control issues with sugar, I ask is that because you will be tempted to take it from me if I dont't?  He says yes.

In this example there is a relationship normal attack - I prompted H to ask for the mint
There is also a self-advocacy normal attack - I prompted H to tell me that he would be tempted if I didn't eat my mint

These notes will often be reviewed during the LCS debrief when we go over how the week went.  They will also be reviewed at the end of each session in a more informal 'Pro's and Con's' session.  Right now this is done verbally, as I don't have any way of analyzing data during session.  If there was a milestone event, such as last week when H spoke in public on a microphone at the Edward M. Kennedy Institute, I will record in a Google document of my weekly log.  As I am typing this, I am seeing a new aspect of the self-review: the milestone timeline.  Each important event to be dropped onto a timeline and viewed at the end of a quarter/semester/year.

**Comment by ClarenceDowSpielman** [comment]
It's clear to me now that these are some of the key elements of my method.
1.)  Involving the client in the creation of LCS categories
2.)  Daily, weekly, semesterly and yearly self-reviews
3.)  Using data in self-reviews with clients
4.)  Using a reward system that does not have black and white consequences - i.e. you did this so you won't earn experience points.  Rather the self-reviews themselves facilitate naturalistic consequences - i.e. you got upset and threw a bottle at me today, let's process it and see if you can learn something.  Maybe there will even be some experience points hiding there!

**Comment by dazzaji** [comment]
Can you try a bulleted short list like this:

| Key Methods | Spreadsheet Data |
| --- | --- |
| Content from cell 1 | Content from cell 2 |
| Content in the first column | Content in the second column |

**Comment by ClarenceDowSpielman** [comment]
Not exactly clear on the model you're suggesting...something like this?  

| Key Methods | Details |
| --- | --- |
| 1.)  Input from client, parents, past and current treatment team in forming categories aka skills and behaviors on which data is collected | Category examples: Waiting, Self-determination, Self-Advocacy, Public Transportation, Relationships, Denial/restriction |
|  | Drives ownership for client; includes all stakeholders |
| 2.)  Use of Life Credits | Earned in each category.  Values determined by treatment team |
|  | Ex. Transition: prompted w/ behavior = 1 LC, prompted w/o behavior = 2 LC, unprompted = 3 LC |
|  | Can only be earned, and never lost |
|  | Treatment team determines how many LC's equal a level |
|  | Levels are exchanged for an agreed upon tangible or privilege, ex. 1 level = $5 |
| 3.)  Data collection in Evernote | Includes times, locations, and shorthand notes for noteworthy events |
| 4.)  Organization of data | a.)  Master Google Spreadsheet of all data to date in every category, with totals for each day and each week |
|  | b.)  Apple Numbers spreadsheets of each week with the following data arrays and graphical representations: |
|  | i.)  Line graph of total LC's earned each week from beginning of program |
|  | ii.)  Side-by-side pie graphs of percentage breakdown of all categories from current week and past week |
|  | iii.)  Side-by-side line graphs of total LC's earned each day from current week and past week |
|  | iv.)  Bar graph of total LC's earned in each category for each week from beginning of program |
|  | v.)  Line graph of total LC's earned in that week's featured category for each week from beginning of program |
| 5.)  Storage in Google Spreadsheet, Numbers and Google Doc | a.)  Master Google Spreadsheet of all data to date |
|  | b.)  Weekly 'LCS Debrief' Numbers spreadsheets of each week with graphical representations of data |
|  | c.)  Weekly logs in Google Docs with notable events, milestones, misc. relevant documentation |
| 6.)  Weekly 'LCS Debrief' | a.)  Use LCS Debrief spreadsheet of previous week in first session of each week to analyze data, view graphs and practice spreadsheet skills |
|  | b.)  One category featured each week. |
|  | i.)  View line graph of total LC's earned for each week from beginning of program |
|  | ii.)  Compare to line graph of total LC's earned in all categories for each week from beginning of program; identify trends |
|  | iii.)  Generate definition in client's own language |
|  | iv.)  List examples in the world and client's own life |
|  | c.)  Sign-off on LCS Debrief form. |
| 7.)  Daily Self-review | At the end of each session, first review Evernotes and look for pros and cons.  Then prompt self-review with client: "It's time for Pro's and Con's.  Can you think of any?" |
|  | _Want to incorporate graphs into this with app._ |
| 8.)  Use of LCS in session | a.)  At random times comment, "I noticed that you just earned __LC's in category __" to prompt self-review and self-awareness |
|  | b.)  If client is non-compliant, casually remark, "Well, it is up to you if you want to earn LC's."  Refer back to client's goals if non-compliance persists. |
|  | c.)  Use categories as talking points.  Ex. If client is working on relationships, therapist can share about a success or challenge in one of their own relationships. |
|  | d.)  'Mining for LC's' |
|  | i.)  In session therapist may prompt, "How was your weekend/day?  Is there anything you'd like to mine for LC's? |
|  | ii.)  If client says, "Yes", go through event and break it down across the LCS categories of that client's program |
|  | iii.)  Ex.  "My mom put Net Nanny on my computer on Saturday.  Later I got really mad at my dad and swore at him, but I didn't throw my computer.  Then on Sunday I suggested that we go golfing."  Client experienced denial and had to self-regulate, but then vented anger towards his dad.  He did show self-control in not throwing his computer, which has been a past behavior.  For this he earns LC's for Denial and Self-regulation.  Then on Sunday he did relationship maintenance with his dad, and earns significant LC's for Relationships. |
| 9.)  Use of LCS outside of session | Other stakeholders may collaborate and apply LCS in various contexts |
|  | In community with therapist |
|  | In academic session with special educators |
|  | In home with parents while working on specific skills such as chores |
| 9.)  Intrinsic motivation |  |
| 10.)  Gamification |  |

**Comment by dazzaji** [comment]
Yes indeed, something like that. Something exactly like that. 

Just ... exactly that.

**Comment by ClarenceDowSpielman** [comment]
Booyah

**Comment by dazzaji** [comment]
To clarify, you seem to have answered the question of this issue in your table. Therefor I recommend you take the table and copy paste it into a wiki page titled something like "Method and Corresponding App Function". Then copy link of that new wiki page and past it into a comment to this issue with words like "question answered and now exists for further iteration at this project wiki page: http://GitHub wiki page .com".  Then select "comment and close issue" so the closed issue will include all the relevant info in case you need it later or for later new people on the project to understand what happened and is happening.

**Comment by ClarenceDowSpielman** [comment]
Question answered and now exists for further iteration at this project wiki page: https://github.com/ClarenceDowSpielman/project-prep/wiki/Method-and-Corresponding-App-Function
