### ISSUE TITLE
Dr. Askin's IP Audit

### ISSUE THREAD

**Issue by ClarenceDowSpielman** [ClarenceDowSpielman/project-prep#11]
What do you need from me to do this?

**Comment by dazzaji** [comment]
When the course starts you should book time with Prof Askin to get a legal assessment of the project and any Intellectual Property or other legal protections or other measures might be appropriate.  He is offering this to all projects in the course.

**Comment by ClarenceDowSpielman** [comment]
Consulted with Prof. Askin.  [Issue](https://github.com/ClarenceDowSpielman/project-prep/issues/55) follow-up
