### ISSUE TITLE
In-person presentation

### ISSUE THREAD

**Issue by ClarenceDowSpielman** [ClarenceDowSpielman/project-prep#14]
I have my first in-person meeting with the director of a fairly large private organization for whom I have done some work in the past.  She wants to know more and would be glad to help get the prototype out to kids/young adults for testing.

Need to get clear on:

1.)  Talking points
2.)  App vs. method

Very excited.

**Comment by dazzaji** [comment]
Take care not to get ahead of what you are presently prepared to discuss and I recommend keeping your ask at this point to the invitation we discussed for the roles reviewer/feedback (maybe appropriate for this person) or volunteer team member (especially to help you hone the method and/or spreadsheet and/or app based implementation of the spreadsheet)

**Comment by ClarenceDowSpielman** [comment]
1.)  Addressed by sticking to presenting what I am currently doing and speaking to the possibility of an upgrade through app prototype.

2.)  Question answered and now exists for further iteration at https://github.com/ClarenceDowSpielman/project-prep/wiki/Method-and-Corresponding-App-Function
