### ISSUE TITLE
Points to be discussed on our chat

### ISSUE THREAD

**Issue by ClarenceDowSpielman** [ClarenceDowSpielman/project-prep#16]
1.)  Confirm pre-reg signup is complete
2.)  Any bites on getting a team together?  Anything necessary to do on my end?
3.)  January timeline (as best as you know)
4.)  Clarence in Costa Rica Jan 22nd - 30th

**Comment by ClarenceDowSpielman** [comment]
Also had some thoughts on formatting the github wiki to use as website.  Could move the welcome page over to be the main wiki page and then have the welcome page say Welcome! with link to Wiki and my website.

**Comment by dazzaji** [comment]
Got to push back the call time tonight. Am with people from my lab till about 10. Want to schedule for tomorrow.

**Comment by ClarenceDowSpielman** [comment]
Okay I have a window between 1 and 5.

**Comment by dazzaji** [comment]
Some time between 3:30-5:00pm would work. Is there a good number I can call you at during that period? 

---

   |   Daniel "Dazza" Greenwood, JD
   |   Personal: DazzaGreenwood.com
   |   Consulting Service: CIVICS.com
   |   MIT Research: Law.MIT.edu
   |     Email: dazza@CIVICS.com
   |     Mobile: 617.500.3644

**Comment by ClarenceDowSpielman** [comment]
Great lets do 3:30

**Comment by dazzaji** [comment]
Pre-Reg is complete. 

Timing: January Rapid Prototype time is Tue/Wed Jan 12/13 from 2-4pm. Be there or have a proxy there on your behalf for both sessions and you will make more progress but one session is fine.  

I found an MIT undergrad  who might be a good fit and also have some Blockchain developers who expressed interest. There is also a grad student in my lab who may be interested. 

Please create an issue called "is this test data set sufficient for IAP prototype?" with a link to the test data set going to an imaginary "john doe" for review and I'll use that for him to get familiar. We should talk after you have a link to that data.

**Comment by ClarenceDowSpielman** [comment]
Great.  I'm still unclear as to the 'invitation to work with other people along the lines that you and I have discussed at length already' - above and beyond Jan 12th and 13th.  Is this in reference to colleagues whom I have invited to test the app?  Collaborating with the Medialab fellow using sociometric badges?  Does this include more time to work with my team on site or remotely?  If during work hours I need to know so I can plan ahead - I have clients booked all week and can accommodate if given notice.

**Comment by ClarenceDowSpielman** [comment]
And thank you for doing all of this :)

**Comment by dazzaji** [comment]
When you are paired with one or more people who will help you prototype, set up one or more meetings with them via phone, hangout, etc.  If this is hard to do, try using this service to set up one or more meetings: https://doodle.com

**Comment by dazzaji** [comment]
issue closed?

**Comment by ClarenceDowSpielman** [comment]
Finishing John Doe data set.  Will close once link is posted to new issue.

**Comment by dazzaji** [comment]
ok.  please text me link to the issue with link to the john doe text data set.

**Comment by dazzaji** [comment]
Is this ready to review?

**Comment by ClarenceDowSpielman** [comment]
Data set ready for review at https://github.com/ClarenceDowSpielman/project-prep/issues/20
