### ISSUE TITLE
Set up Lifecreditsystem.com

### ISSUE THREAD

**Issue by ClarenceDowSpielman** [ClarenceDowSpielman/project-prep#18]
Integrate with blogger site and wiki
Make navigation menu

**Comment by dazzaji** [comment]
I suggest just point it to your wiki for the moment.  we can do this next week and create a nav menu.

alternative: you can set up the blog on your own.  if you want to try to set up the blog, then look at the google blogger help or search youtube for tutorials or just click around and figure out how things work. unless you feel very comfy setting up and managing the blog then don't do it.  there are no blog services available for ongoing support beyond whatever you can provide for yourself.  therefore, i suggest you keep using and get good at the github wiki and just point your domain at it.  you can also point your domain name to a github pages landing page (aka splash page) at github for a simple to understand and look at page for any person (eg that is what i do at these sites: mit.edu/law and civics.com and dazzagreenwood.com and citylawtech.org).

**Comment by ClarenceDowSpielman** [comment]
Website set up and linked to [github landing page](lifecreditsystem.com)
