### ISSUE TITLE
What is the difference between roles and personae?

### ISSUE THREAD

**Issue by ClarenceDowSpielman** [ClarenceDowSpielman/project-prep#57]
[Current presentation on slides](https://docs.google.com/presentation/d/1ZG0jRt5Ak5Xl9FQ_Ursiqk_1-BPXvAHTWGvGlw-fxZY/edit#slide=id.gf98296235_0_42)

**Comment by dazzaji** [comment]
Example persona: webdesign.tutsplus.com/articles/defining-and-applying-personas-to-ux-design--webdesign-7561

---

   |   Daniel "Dazza" Greenwood, JD
   |   Personal: DazzaGreenwood.com
   |   Consulting Service: CIVICS.com
   |   MIT Research: Law.MIT.edu
   |     Email: dazza@CIVICS.com
   |     Mobile: 617.500.3644

**Comment by ClarenceDowSpielman** [comment]
Difference clarified and reflected in [Current presentation on slides](https://docs.google.com/presentation/d/1ZG0jRt5Ak5Xl9FQ_Ursiqk_1-BPXvAHTWGvGlw-fxZY/edit#slide=id.gf98296235_0_42)
