### ISSUE TITLE
Schedule check in on prep for IAP 

### ISSUE THREAD

**Issue by dazzaji** [ClarenceDowSpielman/project-prep#6]
When are potential good day/time slots for you?

**Comment by ClarenceDowSpielman** [comment]
I'll respond tomorrow, thank you.

On Thu, Dec 10, 2015 at 10:48 PM, Dazza Greenwood notifications@github.com
wrote:

> When are potential good day/time slots for you?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ClarenceDowSpielman/project-prep/issues/6.

## 

Clarencedow.com
Facebook.com/powerplaypresence
Beachbodycoach.com/clarencedow
Myshakeology.com/clarencedow

**Comment by ClarenceDowSpielman** [comment]
Availability for next week:

Tuesday:  after 6 pm
Wednesday:  before 11 am
Thursday:  before 12 pm & after 6 pm
Friday:  before 2 pm
Saturday:  before 4 pm
Sunday:  before 9 am, after 1 pm

**Comment by ClarenceDowSpielman** [comment]
Following up on this.

**Comment by ClarenceDowSpielman** [comment]
Availability for this week and next (this week is preferable):

Tuesday (12/22): after 6 pm
Wednesday: after 9 pm
Thursday: all day
Friday: all day
Saturday: n/a
Sunday: after 12pm
Monday (12/28): before 12pm
Tuesday: after 6 pm
Wednesday: after 9 pm
Thursday: all day
Friday: all day
Saturday: all day
Sunday: after 12pm

**Comment by ClarenceDowSpielman** [comment]
Updated availability for week of Dec. 28th:

Monday (12/28): before 12pm, after 9:30 pm
Tuesday: after 6 pm
Wednesday: after 9 pm
Thursday: all day
Friday: all day
Saturday: all day
Sunday: after 12pm

**Comment by dazzaji** [comment]
Let's shoot for Mon 28th after 9:30 or as fall back can do Wed after 9. Please text before calling I case I need to get into better position to speak. Thanks!

**Comment by ClarenceDowSpielman** [comment]
Great.  Will text you tonight at 9:30.
